If you are just a student and dont have enough computation power and/or training set  
Just use a pre-trained model as we do  
Using pre-trained model from there: https://github.com/endernewton/tf-faster-rcnn  
Patching for using just CPU: https://github.com/endernewton/tf-faster-rcnn/issues/72  

In [1]:
import os 
import sys

this_dir = os.getcwd()
print(this_dir)

# Add lib to PYTHONPATH
lib_path = os.path.join(this_dir, 'tf-faster-rcnn', 'lib')
sys.path.insert(0, lib_path)
print(lib_path)

coco_path = os.path.join(this_dir, 'tf-faster-rcnn', 'data', 'coco', 'PythonAPI')
sys.path.insert(0, coco_path)

/home/jovyan/work/NetsLab
/home/jovyan/work/NetsLab/tf-faster-rcnn/lib


In [2]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from model.config import cfg
from model.test import im_detect
from model.nms_wrapper import nms

from utils.timer import Timer
import tensorflow as tf
import matplotlib.pyplot as plt
print(tf.__version__)
import numpy as np
import os, cv2
import argparse

from nets.vgg16 import vgg16
from nets.resnet_v1 import resnetv1

1.3.0


In [3]:
% matplotlib inline

In [4]:
anchor_scales = [2, 4, 8, 16, 32] 
CLASSES = ('background',
'person', 'bicycle', 'car', 'motorcycle', 'airplane',
'bus','train', 'truck', 'boat', 'traffic light', 'fire hydrant',
'stop sign', 'parking meter','bench', 'bird', 'cat', 'dog',
'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe',
'backpack','umbrella', 'handbag', 'tie', 'suitcase', 'frisbee',
'skis', 'snowboard', 'sports ball', 'kite','baseball bat', 'baseball glove',
'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup',
'fork', 'knife', 'spoon', 'bowl','banana', 'apple', 'sandwich', 'orange',
'broccoli','carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'couch',
'potted plant', 'bed', 'dining table','toilet', 'tv', 'laptop', 'mouse', 'remote',
'keyboard', 'cell phone', 'microwave', 'oven','toaster', 'sink', 'refrigerator',
'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush')


In [5]:
def vis_detections(class_name, dets, ax, thresh=0.5):
    """Draw detected bounding boxes."""
    inds = np.where(dets[:, -1] >= thresh)[0]
    if len(inds) == 0:
        return

    
    for i in inds:
        bbox = dets[i, :4]
        score = dets[i, -1]

        ax.add_patch(
            plt.Rectangle((bbox[0], bbox[1]),
                          bbox[2] - bbox[0],
                          bbox[3] - bbox[1], fill=False,
                          edgecolor='red', linewidth=3.5)
            )
        ax.text(bbox[0], bbox[1] - 2,
                '{:s} {:.3f}'.format(class_name, score),
                bbox=dict(facecolor='blue', alpha=0.5),
                fontsize=14, color='white')


    #plt.draw()
    #plt.savefig(save_path)
    #plt.show()

In [6]:
def demo(sess, net, image_name):
    """Detect object classes in an image using pre-computed object proposals."""

    # Load the demo image
    im_file = os.path.join(this_dir, "data/images", image_name)
    im_save_file = os.path.join(this_dir, "data/images_out/fasterrcnn_vgg", image_name)
    im = cv2.imread(im_file)

    # Detect all object classes and regress object bounds
    timer = Timer()
    timer.tic()
    scores, boxes = im_detect(sess, net, im)
    timer.toc()
    print('Detection took {:.3f}s for {:d} object proposals'.format(timer.total_time, boxes.shape[0]))

    # Visualize detections for each class
    CONF_THRESH = 0.8
    NMS_THRESH = 0.3
    
    im = im[:, :, (2, 1, 0)]
    fig, ax = plt.subplots(figsize=(12, 12))
    ax.imshow(im, aspect='equal')
    for cls_ind, cls in enumerate(CLASSES[1:]):
        cls_ind += 1 # because we skipped background
        cls_boxes = boxes[:, 4*cls_ind:4*(cls_ind + 1)]
        cls_scores = scores[:, cls_ind]
        dets = np.hstack((cls_boxes,
                          cls_scores[:, np.newaxis])).astype(np.float32)
        keep = nms(dets, NMS_THRESH)
        dets = dets[keep, :]
        bbox = dets[:,:4]
        score = dets[:,-1]
        #print(cls)
        #print(bbox[score>CONF_THRESH], score[score>CONF_THRESH])
        vis_detections(cls, dets, ax, thresh=CONF_THRESH)
    plt.axis('off')
    plt.tight_layout()
    plt.savefig(im_save_file)
    plt.show()

In [ ]:
cfg.TEST.HAS_RPN = True  # Use RPN for proposals

# model path
tfmodel = os.path.join(this_dir, "data", "Faster-RCNN/vgg16_faster_rcnn_iter_1190000.ckpt")


if not os.path.isfile(tfmodel + '.meta'):
    raise IOError(('{:s} not found.\nDid you download the proper networks from '
                   'our server and place them properly?').format(tfmodel + '.meta'))

# init session
sess = tf.Session()
# load network
net = vgg16()
net.create_architecture("TEST", len(CLASSES), tag='default', anchor_scales=[4, 8, 16, 32])
saver = tf.train.Saver()
saver.restore(sess, tfmodel)

print('Loaded network {:s}'.format(tfmodel))

# im_names = ['000456.jpg', '000542.jpg', '001150.jpg',
#             '001763.jpg', '004545.jpg']
# for im_name in im_names:
#     print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
#     print('Demo for data/demo/{}'.format(im_name))
#     demo(sess, net, im_name)
# plt.show()

# Performance measurements block
import time
from tqdm import tqdm
perf_image = this_dir + "/data/images/" + "000542.jpg"
times = list()
im = cv2.imread(perf_image)
# for i in tqdm(range(100)):
#     timestart = time.time()
#     im_detect(sess, net, im)
#     times.append(time.time() - timestart)
# print(times)    
# performance = np.array(times)
# print("Mean:", np.mean(performance))
# print("Median:", np.median(performance))
# print("Q25:", np.percentile(performance, 25))
# print("Q75:", np.percentile(performance, 75))

sc, bx = im_detect(sess, net, im)
print(sc.shape, bx.shape)
exit()
##############################################################

########### Accuracy block ####################
import json
from tqdm import tqdm
ann_file = this_dir + '/data/annotations/instances_val2017.json'
test_images_path = this_dir + '/data/test_data/'
test_image_names = sorted(os.listdir(test_images_path))
cat_id_to_real_id = \
    {1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10, 11: 11, 13: 12, 14: 13, 15: 14, 16: 15, 17: 16,
     18: 17, 19: 18, 20: 19, 21: 20, 22: 21, 23: 22, 24: 23, 25: 24, 27: 25, 28: 26, 31: 27, 32: 28, 33: 29, 34: 30,
     35: 31, 36: 32, 37: 33, 38: 34, 39: 35, 40: 36, 41: 37, 42: 38, 43: 39, 44: 40, 46: 41, 47: 42, 48: 43, 49: 44,
     50: 45, 51: 46, 52: 47, 53: 48, 54: 49, 55: 50, 56: 51, 57: 52, 58: 53, 59: 54, 60: 55, 61: 56, 62: 57, 63: 58,
     64: 59, 65: 60, 67: 61, 70: 62, 72: 63, 73: 64, 74: 65, 75: 66, 76: 67, 77: 68, 78: 69, 79: 70, 80: 71, 81: 72,
     82: 73, 84: 74, 85: 75, 86: 76, 87: 77, 88: 78, 89: 79, 90: 80}
    
def parse_annotation(ann_file, img_dir, labels=[]):
    all_imgs = dict()
    seen_labels = set()
    with open(ann_file) as f:
        inst = json.load(f)
    boxes = {image['id']:dict() for image in inst['images']}
    cats = inst["categories"]
    for ann in inst['annotations']:
        obj = {}
        real_id = cat_id_to_real_id[ann['category_id']]
        namename = cats[real_id-1]["name"]
        seen_labels.add(namename)
        obj = []
        obj.append(int(round(ann['bbox'][1])))
        obj.append(int(round(ann['bbox'][0])))
        obj.append(int(round(ann['bbox'][1] + ann['bbox'][3])))        
        obj.append(int(round(ann['bbox'][0] + ann['bbox'][2])))
        if namename in boxes[ann["image_id"]]:
            boxes[ann['image_id']][namename].append(obj)
        else:
            boxes[ann['image_id']][namename] = [obj]
    for image in inst['images']:
        all_imgs[os.path.join(img_dir,image['file_name'])] =  boxes[image['id']]
    return all_imgs, seen_labels

imgs, labels = parse_annotation(ann_file, test_images_path)
        
def bb_intersection_over_union(boxA, boxB):
    # determine the (x, y)-coordinates of the intersection rectangle
    xA = max(boxA[0], boxB[0])
    yA = max(boxA[1], boxB[1])
    xB = min(boxA[2], boxB[2])
    yB = min(boxA[3], boxB[3])
 
    # compute the area of intersection rectangle
    interArea = (xB - xA + 1) * (yB - yA + 1)
 
    # compute the area of both the prediction and ground-truth
    # rectangles
    boxAArea = (boxA[2] - boxA[0] + 1) * (boxA[3] - boxA[1] + 1)
    boxBArea = (boxB[2] - boxB[0] + 1) * (boxB[3] - boxB[1] + 1)
 
    # compute the intersection over union by taking the intersection
    # area and dividing it by the sum of prediction + ground-truth
    # areas - the interesection area
    iou = interArea / float(boxAArea + boxBArea - interArea)
    if iou < 0:
        return 0
    # return the intersection over union value
    return iou

def compare_objdetect_accuracy(grrdict, predictdict):
    accs = []
    for key in grrdict:
        if key not in predictdict:
            accs += [0]* len(grrdict[key])
        else:
            for bbx in grrdict[key]:
                bbxaccs = []
                for bbox in predictdict[key]:
                    bbxaccs.append(bb_intersection_over_union(bbx, bbox))
                accs.append(max(bbxaccs))
            if len(grrdict[key]) < len(predictdict[key]):
                accs += [0]* (len(predictdict[key]) - len(grrdict[key]))
    for key in predictdict:
        if key not in grrdict:
            accs += [0]*len(predictdict[key])
    return np.mean(accs)

accuracys = []
for iname in tqdm(test_image_names):
    finame = test_images_path + iname
    print(iname)
    img = cv2.imread(finame)
    scores, boxes = im_detect(sess, net, img)
    prdctns = dict()
    for cls_ind, cls in enumerate(CLASSES[1:]):
        cls_ind += 1 # because we skipped background
        cls_boxes = boxes[:, 4*cls_ind:4*(cls_ind + 1)]
        cls_scores = scores[:, cls_ind]
        dets = np.hstack((cls_boxes,
                          cls_scores[:, np.newaxis])).astype(np.float32)
        keep = nms(dets, 0.3)
        dets = dets[keep, :]
        score = dets[:,-1]
        bbox = dets[:,:4][score>0.8]
        bbox = np.round(bbox).astype(int)
        if len(bbox) != 0:
            for bb in bbox:
                print(bb)
                if cls in prdctns:
                    prdctns[cls].append(bb)
                else:
                    prdctns[cls] = [bb]

    accuracys.append(compare_objdetect_accuracy(imgs[finame], prdctns))
print(accuracys)
print(np.mean(accuracys))
###############################################




sess.close()

INFO:tensorflow:Restoring parameters from /home/jovyan/work/NetsLab/data/Faster-RCNN/vgg16_faster_rcnn_iter_1190000.ckpt
Loaded network /home/jovyan/work/NetsLab/data/Faster-RCNN/vgg16_faster_rcnn_iter_1190000.ckpt
(103, 81) (103, 324)


  0%|          | 0/99 [00:00<?, ?it/s]

000000000139.jpg


  1%|          | 1/99 [00:07<12:09,  7.44s/it]

[419 158 469 295]
[383 172 405 212]
[165 233 186 265]
[293 219 353 315]
[366 218 440 313]
[231 174 266 213]
[  6 166 156 265]
000000000285.jpg


  2%|▏         | 2/99 [00:12<10:29,  6.49s/it]

[  0  53 585 639]
000000000632.jpg


  3%|▎         | 3/99 [00:19<10:23,  6.49s/it]

[ 97 190 114 231]
[248 233 345 315]
[336 222 430 350]
[191 132 241 231]
[  1 266 401 482]
[285   0 583 383]
[487 159 531 177]
000000000724.jpg


  4%|▍         | 4/99 [00:25<10:17,  6.50s/it]

[101 274 145 310]
[122  72 261 229]
000000000776.jpg


  5%|▌         | 5/99 [00:32<10:04,  6.43s/it]

[  0 191 341 626]
000000000785.jpg


  6%|▌         | 6/99 [00:39<10:09,  6.55s/it]

[284  52 493 385]
[204 356 615 396]
000000000802.jpg


  7%|▋         | 7/99 [00:46<10:12,  6.66s/it]

[ 31 268 166 519]
[242 156 407 542]
000000000872.jpg


  8%|▊         | 8/99 [00:52<09:51,  6.50s/it]

[160 126 373 605]
[283 111 436 545]
000000000885.jpg


  9%|▉         | 9/99 [00:59<09:52,  6.58s/it]

[282 181 412 397]
[296  86 394 227]
[596  28 639 254]
[431   0 465  13]
[499   0 553  15]
[400 270 482 311]
000000001000.jpg


 10%|█         | 10/99 [01:05<09:45,  6.58s/it]

[119 150 200 378]
[266 100 352 416]
[328 154 412 469]
[517 187 639 479]
[405 212 535 478]
[199 159 287 418]
[ 41 188 111 395]
[431 105 497 234]
[195 114 270 256]
[ 20 248  68 349]
[ 49 296  96 389]
000000001268.jpg


 11%|█         | 11/99 [01:12<09:43,  6.63s/it]

[403 206 469 295]
[496  91 638 421]
[ 22 213  80 285]
[  0 210  26 285]
[195 225 265 262]
[495 200 594 402]
[556 198 601 355]
000000001296.jpg


 12%|█▏        | 12/99 [01:19<09:36,  6.63s/it]

[ 17   3 410 634]
[175 404 251 466]
[302 147 373 274]
000000001353.jpg


 13%|█▎        | 13/99 [01:26<09:29,  6.62s/it]

[ 63 189 265 469]
[217 157 279 220]
[145 133 224 197]
[188  66 272 171]
000000001425.jpg


 14%|█▍        | 14/99 [01:31<09:16,  6.55s/it]

000000001490.jpg


 15%|█▌        | 15/99 [01:38<09:10,  6.56s/it]

[449 119 502 241]
[358 231 572 246]
000000001503.jpg


 16%|█▌        | 16/99 [01:44<09:03,  6.55s/it]

[298  96 319 151]
[129  15 240 105]
[  0 101 114 233]
[124 179 157 199]
[158 151 316 200]
000000001532.jpg


 17%|█▋        | 17/99 [01:51<08:56,  6.54s/it]

[428 397 490 451]
[  1 377 112 478]
[218 356 425 479]
[200 403 231 429]
[108 377 186 437]
000000001584.jpg


 18%|█▊        | 18/99 [01:56<08:44,  6.47s/it]

[ 76 375  97 429]
[106 387 125 429]
[193 306 233 353]
[128  79 524 536]
[512 315 569 381]
000000001675.jpg


 19%|█▉        | 19/99 [02:02<08:35,  6.45s/it]

[  2   0 325 328]
000000001761.jpg


 20%|██        | 20/99 [02:09<08:32,  6.48s/it]

[152  12 221  85]
[279 139 334 183]
000000001818.jpg


 21%|██        | 21/99 [02:16<08:25,  6.48s/it]

[134   5 638 403]
[  3  36 330 424]
000000001993.jpg


 22%|██▏       | 22/99 [02:23<08:21,  6.51s/it]

[108 249 219 408]
[280 172 595 402]
[  0 240 163 400]
000000002006.jpg


 23%|██▎       | 23/99 [02:29<08:14,  6.51s/it]

[  8 252  52 360]
[315 188 379 247]
[ 9 54 30 79]
[ 41  86 601 416]
[57  6 68 31]
000000002149.jpg


 24%|██▍       | 24/99 [02:36<08:08,  6.51s/it]

[333  70 586 325]
[  4 241 250 407]
[ 78  72 345 341]
[448 301 633 396]
000000002153.jpg


 25%|██▌       | 25/99 [02:42<08:01,  6.50s/it]

[176   0 240 120]
[285 282 466 448]
[373 203 439 347]
[386 183 459 232]
000000002157.jpg


 26%|██▋       | 26/99 [02:49<07:56,  6.53s/it]

[231  48 298 195]
[160  71 236 181]
[ 90  92 158 183]
[ 50  35 108 195]
[124  24 191 172]
[  1  84  57 261]
[313 312 406 376]
[451 262 509 292]
[ 11 155 261 359]
[  0  41 636 413]
000000002261.jpg


 27%|██▋       | 27/99 [02:56<07:51,  6.55s/it]

[272 154 380 289]
000000002299.jpg


 28%|██▊       | 28/99 [03:04<07:48,  6.60s/it]

[  1 126  49 281]
[ 72 191 134 301]
[426 127 483 280]
[138 191 216 294]
[385 196 457 287]
[258 197 335 279]
[109 125 152 273]
[ 62  34 114 128]
[327 194 394 287]
[ 39 133  80 275]
[199 190 278 287]
[206  23 260 109]
[390  36 442 106]
[  1  92  49 163]
[348  27 395 124]
[178 113 224 225]
[ 44  83  95 161]
[110  31 161 118]
[309  27 362 114]
[162  26 211 116]
[259  19 315 119]
[322 129 363 218]
000000002431.jpg


 29%|██▉       | 29/99 [03:10<07:41,  6.59s/it]

[302   0 427 206]
[186 393 403 612]
[ 44 380 193 477]
[  5  99 456 639]
000000002473.jpg


 30%|███       | 30/99 [03:18<07:35,  6.60s/it]

[236  93 379 242]
[440 278 498 382]
[118 341 144 387]
[ 31 329  59 354]
[  3 341  17 353]
000000002532.jpg


 31%|███▏      | 31/99 [03:24<07:28,  6.60s/it]

[182 304 283 466]
[218 444 268 483]
000000002587.jpg


 32%|███▏      | 32/99 [03:30<07:20,  6.58s/it]

000000002592.jpg


 33%|███▎      | 33/99 [03:37<07:14,  6.59s/it]

[220  37 455 240]
000000002685.jpg


 34%|███▍      | 34/99 [03:43<07:07,  6.57s/it]

[350  17 604 440]
[183 103 503 546]
[ 19 213 139 434]
[282  95 362 211]
[590 134 639 190]
000000002923.jpg


 35%|███▌      | 35/99 [03:49<07:00,  6.57s/it]

[151 198 157 214]
[135 237 146 253]
[269 242 282 258]
[171 159 184 166]
000000003156.jpg


 36%|███▋      | 36/99 [03:56<06:53,  6.57s/it]

[ 10  18 435 639]
[253 356 442 595]
000000003255.jpg


 37%|███▋      | 37/99 [04:03<06:48,  6.59s/it]

[294 313 315 351]
[273 315 291 355]
[258 311 275 355]
[236 316 251 357]
000000003501.jpg


 38%|███▊      | 38/99 [04:08<06:39,  6.55s/it]

[ 75 164 255 364]
[122  72 249 219]
000000003553.jpg


 39%|███▉      | 39/99 [04:15<06:33,  6.56s/it]

[127   4 416 331]
[160 215 404 349]
000000003661.jpg


 40%|████      | 40/99 [04:22<06:27,  6.57s/it]

[562  22 637 253]
[ 40   0 586 240]
[ 88 180 479 350]
000000003845.jpg


 41%|████▏     | 41/99 [04:28<06:20,  6.56s/it]

[112   0 186  57]
[123 207 187 267]
[184 184 269 260]
[167  81 207 139]
[259 191 298 265]
[192 253 262 323]
[449   0 499  77]
[  4   6 489 350]
000000003934.jpg


 42%|████▏     | 42/99 [04:35<06:13,  6.56s/it]

[196 109 237 218]
[ 61 128 199 458]
[158  83 210 230]
[295 132 326 181]
[ 38  79 106 339]
[ 92  88 159 178]
[218 278 237 306]
[141 196 374 379]
[189 208 215 228]
000000004134.jpg


 43%|████▎     | 43/99 [04:42<06:08,  6.57s/it]

[ 47  40 292 423]
[219  52 593 422]
[ 13 110  74 260]
[298 121 338 275]
[237 127 279 205]
[576 108 636 419]
[471 112 529 183]
[549 142 578 194]
[517 140 538 184]
[ 66 127  99 209]
[348 137 378 194]
[393 191 438 366]
[207 249 311 338]
000000004395.jpg


 44%|████▍     | 44/99 [04:49<06:01,  6.57s/it]

[  9   0 405 639]
[326 389 424 629]
[172 275 266 632]
000000004495.jpg


 45%|████▌     | 45/99 [04:55<05:54,  6.57s/it]

[  8 163 155 324]
[199 198 499 374]
[193 112 259 176]
000000004765.jpg


 46%|████▋     | 46/99 [05:00<05:46,  6.54s/it]

[215 122 399 380]
[273 347 534 419]
000000004795.jpg


 47%|████▋     | 47/99 [05:06<05:39,  6.52s/it]

[176 135 563 477]
[  4 129 204 472]
[189   0 639 470]
[530 239 639 445]
000000005001.jpg


 48%|████▊     | 48/99 [05:13<05:32,  6.52s/it]

[349  92 526 433]
[ 82 230 201 478]
[441  46 507 164]
[ 46  72 205 357]
[342  51 406 150]
[535  72 634 382]
[  8  36  70 184]
[294  53 353 144]
[217  76 344 360]
[169  35 272 279]
[235 264 347 476]
[527  55 567 118]
[570 152 592 182]
000000005037.jpg


 49%|████▉     | 49/99 [05:20<05:26,  6.53s/it]

[623 215 639 360]
[ 24 222  40 246]
[  9 218  25 245]
[573 249 601 268]
[105  26 577 374]
000000005060.jpg


 51%|█████     | 50/99 [05:26<05:20,  6.53s/it]

[165 306 313 499]
000000005193.jpg


 52%|█████▏    | 51/99 [05:33<05:14,  6.55s/it]

[293 173 404 394]
[ 76 124 242 423]
[366 212 481 368]
[222  64 264 187]
[368  96 487 269]
[468  52 570 336]
[368  94 390 168]
[ 69 172 114 201]
[366 282 392 312]
000000005477.jpg


 53%|█████▎    | 52/99 [05:41<05:08,  6.56s/it]

[  9  98 639 291]
[ 43 250 150 274]
000000005503.jpg


 54%|█████▎    | 53/99 [05:47<05:01,  6.55s/it]

[ 48 149 262 483]
000000005529.jpg


 55%|█████▍    | 54/99 [05:54<04:55,  6.56s/it]

[ 99 124 250 431]
000000005586.jpg


 56%|█████▌    | 55/99 [06:00<04:48,  6.56s/it]

[144  67 176 157]
[291  62 304 101]
[118 169 201 235]
[273  73 294 110]
[132  92 151 104]
000000005600.jpg


 57%|█████▋    | 56/99 [06:07<04:42,  6.57s/it]

[189 141 550 360]
[101   2 381 227]
[ 49   0 626 360]
000000005992.jpg


 58%|█████▊    | 57/99 [06:14<04:36,  6.57s/it]

[  0 213  30 265]
[ 22 134 235 375]
[204 145 558 424]
[557 184 639 416]
000000006012.jpg


 59%|█████▊    | 58/99 [06:20<04:28,  6.56s/it]

[358 141 553 502]
[ 89 131 281 496]
[332  17 463 346]
[198 241 454 470]
000000006040.jpg


 60%|█████▉    | 59/99 [06:27<04:22,  6.57s/it]

[263 197 282 224]
[448 180 481 220]
[331 197 353 229]
[299 200 316 226]
[375 198 402 228]
[ 36  86 626 319]
[  2 174  50 215]
000000006213.jpg


 61%|██████    | 60/99 [06:34<04:16,  6.58s/it]

[586 289 639 314]
[408 269 505 289]
000000006460.jpg


 62%|██████▏   | 61/99 [06:41<04:10,  6.59s/it]

[276 138 332 211]
000000006471.jpg


 63%|██████▎   | 62/99 [06:49<04:04,  6.60s/it]

[262  63 355 300]
[ 17 142 128 323]
[ 88 189 235 326]
[ 85  71 140 140]
[397  60 453 113]
[212  73 271 130]
[167  74 219 133]
[ 24  95  73 148]
[ 50  81  78 133]
[  1  92  20 149]
[38  0 69 13]
[295  26 362 108]
[214 230 242 263]
000000006614.jpg


 64%|██████▎   | 63/99 [06:55<03:57,  6.59s/it]

000000006723.jpg


 65%|██████▍   | 64/99 [07:02<03:51,  6.60s/it]

[102 197 111 221]
[171 203 197 223]
[202 201 242 229]
[283 199 302 212]
[363 191 395 223]
000000006763.jpg


 66%|██████▌   | 65/99 [07:09<03:44,  6.60s/it]

[  5  79 300 493]
[174 120 353 448]
[  1 213  45 336]
[146 233 178 393]
000000006771.jpg


 67%|██████▋   | 66/99 [07:16<03:38,  6.61s/it]

[138 123 441 425]
[545 148 638 426]
[373 154 579 415]
[ 63 139 240 417]
[390 134 478 234]
[  0   9  87 386]
[565 131 633 225]
000000006818.jpg


 68%|██████▊   | 67/99 [07:23<03:31,  6.61s/it]

[353 463 424 583]
000000006894.jpg


 69%|██████▊   | 68/99 [07:29<03:24,  6.60s/it]

[176  12 639 478]
[ 80  41 617 479]
[ 32  90 250 474]
000000006954.jpg


 70%|██████▉   | 69/99 [07:35<03:18,  6.60s/it]

[  0 105 160 458]
[364 152 445 322]
[413 116 623 374]
[140 135 265 317]
[197 131 359 359]
[254 235 353 336]
[458 234 603 361]
000000007088.jpg


 71%|███████   | 70/99 [07:42<03:11,  6.60s/it]

[180 205 274 465]
[ 89 174 305 268]
[186 284 219 354]
000000007108.jpg


 72%|███████▏  | 71/99 [07:48<03:04,  6.60s/it]

[102  14 507 423]
[355  56 623 419]
000000007278.jpg


 73%|███████▎  | 72/99 [07:55<02:58,  6.60s/it]

[194  69 324 156]
000000007281.jpg


 74%|███████▎  | 73/99 [08:02<02:51,  6.61s/it]

[  1 227  31 269]
[552 192 566 223]
[391 133 472 285]
[458 120 537 271]
[254 199 263 207]
[593 202 608 214]
[571 201 583 213]
[470 182 543 360]
[345 184 447 360]
000000007386.jpg


 75%|███████▍  | 74/99 [08:09<02:45,  6.62s/it]

[137  23 570 380]
[441 159 562 236]
[181 279 223 325]
000000007511.jpg


 76%|███████▌  | 75/99 [08:16<02:38,  6.62s/it]

[375 242 507 476]
[269 274 282 303]
[237 280 249 306]
[155 251 591 310]
[205 126 223 160]
000000007574.jpg


 77%|███████▋  | 76/99 [08:22<02:32,  6.62s/it]

[293 289 343 388]
[504 304 534 387]
[483 299 508 376]
[106  69 148  88]
[439 342 476 366]
[342 242 422 357]
[183 356 302 410]
[ 39 367 173 433]
[ 26 358 363 458]
[  0 154 107 387]
[328 116 348 139]
[206  55 230  92]
000000007784.jpg


 78%|███████▊  | 77/99 [08:28<02:25,  6.61s/it]

[ 82  83 342 297]
[231 139 327 307]
000000007795.jpg


 79%|███████▉  | 78/99 [08:35<02:18,  6.61s/it]

[  0 215 447 416]
[118 195 459 302]
[512  91 622 304]
000000007816.jpg


 80%|███████▉  | 79/99 [08:43<02:12,  6.62s/it]

[247  35 293 142]
[501  54 544 166]
[567  48 616 170]
[256  72 439 306]
[416 120 475 174]
[363 107 387 165]
[491  57 517 159]
[566  54 589 118]
[241 148 471 354]
000000007818.jpg


 81%|████████  | 80/99 [08:50<02:05,  6.63s/it]

[ 13 261 118 310]
[258  62 384 307]
[  9 257 613 420]
[288 216 360 315]
000000007977.jpg


 82%|████████▏ | 81/99 [08:57<01:59,  6.63s/it]

[108 150 266 413]
[199 346 269 425]
[194 404 238 425]
000000007991.jpg


 83%|████████▎ | 82/99 [09:04<01:52,  6.64s/it]

000000008021.jpg


 84%|████████▍ | 83/99 [09:10<01:46,  6.64s/it]

[243  98 439 376]
[  0 255 312 476]
[426 285 639 479]
[314 197 341 309]
000000008211.jpg


 85%|████████▍ | 84/99 [09:17<01:39,  6.64s/it]

[325 205 408 354]
[415 183 479 348]
[135 172 257 310]
[ 20 179 184 308]
[478 318 541 352]
[557 149 603 217]
000000008277.jpg


 86%|████████▌ | 85/99 [09:22<01:32,  6.62s/it]

[ 31  38 483 389]
000000008532.jpg


 87%|████████▋ | 86/99 [09:29<01:26,  6.62s/it]

[153  16 639 421]
[418 366 494 424]
000000008629.jpg


 88%|████████▊ | 87/99 [09:34<01:19,  6.60s/it]

[236 429 414 613]
[ 12  31 399 393]
[434  22 619 191]
[434 234 619 402]
[ 39 438 204 598]
000000008690.jpg


 89%|████████▉ | 88/99 [09:40<01:12,  6.60s/it]

[ 95  18 378 446]
[328  78 512 327]
[ 92  13 181 361]
[342 301 639 476]
[ 51 255 521 478]
000000008762.jpg


 90%|████████▉ | 89/99 [09:47<01:06,  6.61s/it]

[  1 278  27 304]
[ 57  85  78 148]
[162 102 187 147]
[502 229 518 243]
[493 181 516 228]
[ 87 102 106 129]
000000008844.jpg


 91%|█████████ | 90/99 [09:54<00:59,  6.61s/it]

[352  54 588 306]
[339 186 372 244]
[333 241 632 398]
000000008899.jpg


 92%|█████████▏| 91/99 [10:00<00:52,  6.60s/it]

[ 10 351  70 452]
[138 402 187 494]
000000009378.jpg


 93%|█████████▎| 92/99 [10:07<00:46,  6.61s/it]

[ 59  44 469 396]
[423 336 479 391]
[520 288 591 393]
[477 320 527 386]
[400 340 434 390]
[183 213 362 255]
[325 328 365 385]
000000009400.jpg


 94%|█████████▍| 93/99 [10:14<00:39,  6.60s/it]

[144  93 288 269]
[314  83 453 280]
[  3  93 105 183]
[469 101 638 420]
[272  59 365 229]
[563  46 628 123]
[462  67 529 214]
[190 266 214 317]
[250 410 320 475]
[ 83 210 209 297]
[  3 173 105 252]
[ 62 307 266 479]
[267 220 447 444]
[461 355 523 383]
[319 361 468 473]
000000009448.jpg


 95%|█████████▍| 94/99 [10:20<00:32,  6.60s/it]

[133 107 381 634]
[  4   0 550 402]
000000009483.jpg


 96%|█████████▌| 95/99 [10:26<00:26,  6.60s/it]

[ 35  76 177 479]
[303  73 383 248]
[451 208 580 350]
[166 258 304 336]
[376 362 408 378]
[310 318 425 360]
000000009590.jpg


 97%|█████████▋| 96/99 [10:33<00:19,  6.60s/it]

[373 169 457 264]
[  3  55 263 419]
[250 175 328 260]
[511 113 637 256]
[128 155 234 294]
[484 247 521 327]
[429 229 449 278]
[347 272 388 309]
[541 214 572 237]
[424 273 471 307]
[289 274 322 293]
[321 272 349 289]
[141 241 626 416]
[178  95 198 124]
000000009769.jpg


 98%|█████████▊| 97/99 [10:40<00:13,  6.60s/it]

[137 200 183 275]
[103 178 467 372]
000000009772.jpg


 99%|█████████▉| 98/99 [10:46<00:06,  6.59s/it]

[275 231 329 350]
[131 557 416 630]
[423  92 515 186]
[327 379 403 399]
[176 379 256 397]
[  1 447  57 507]
000000009891.jpg


100%|██████████| 99/99 [10:52<00:00,  6.59s/it]

[ 79 100 205 292]
[196  97 349 409]
[307 113 353 154]
[358  88 639 308]
[171 241 309 403]
[425 233 494 336]
[3.6068274776212839, 0.69193521707093342, 0.20748155538807711, 0.090879728945972821, 0.12900516366787226, 0.067589688860637542, 0.2720517441412017, 0.17176304648139007, 2.2741793074468819, 0.15165115250036387, 2.3882269596060333, 0.12586609512220845, 0.15270961837542765, 0.0, 0.0, 0.078110198003736253, 0.14146680116370655, 3.2266494380873554, 0.24430365089913209, 0.086504470783946769, 0.40137031383102439, 0.91432192478520014, 0.69953808501216219, 0.15778054173576561, 0.38930042149752075, 0.17483655166732023, 0.00011195283054073218, 6.399723787757889, 0.073335917922913482, 15.744403710257728, 0.0059433372061846457, 0.0, 0.0018754850392342847, 0.083066560569881945, 0.057360609707180106, 0.19862395253724108, 1.8751103459780638, 0.20259298410064974, 0.3079388448644555, 0.05750333709826471, 0.75040747369235972, 0.15932239037219875, 4.3306049833866975, 0.15760937902647293, 0.1417941931

In [ ]:
path = this_dir + '/data/images/test_data'
image_names = sorted(os.listdir(path))